In [1]:
from kernel_helmholtz import k_ff_jax, k_fu_jax, k_uf_jax, rbf_kernel_single_x, rbf_kernel_single_t, k_ff, k_uf, k_fu, k_uu
import numpy as np
from jax import grad, jit, vmap
import jax.numpy as jnp



In [16]:
x = np.linspace(-5,5,15)
y = np.linspace(-2,3,15)
t = np.linspace(0,1,15)
s = np.linspace(0,2,15)
xt = np.hstack((x.reshape(-1,1),t.reshape(-1,1)))
ys = np.hstack((y.reshape(-1,1),s.reshape(-1,1)))
params = [1,1,1,1]

In [17]:
print(np.allclose(k_ff(xt,ys,params),k_ff_jax(xt,ys,params)))
print(np.allclose(k_uf(xt,ys,params),k_uf_jax(xt,ys,params)))
print(np.allclose(k_fu(xt,ys,params),k_fu_jax(xt,ys,params)))

Traced<ShapedArray(float32[2])>with<BatchTrace(level=2/0)> with
  val = Traced<ShapedArray(float32[15,2])>with<DynamicJaxprTrace(level=1/0)>
  batch_dim = 0
True
Traced<ShapedArray(float32[])>with<BatchTrace(level=3/0)> with
  val = Traced<ShapedArray(float32[15])>with<BatchTrace(level=2/0)> with
    val = Traced<ShapedArray(float32[15,15])>with<DynamicJaxprTrace(level=1/0)>
    batch_dim = 0
  batch_dim = 0
Traced<ShapedArray(float32[15,15])>with<DynamicJaxprTrace(level=1/0)>
False
False


In [6]:
print(k_uf(xt,ys,params))
print(k_uf_jax(xt,ys,params))

[[-1.2096275e-02  5.1417255e-15]
 [-2.5165852e-20 -5.4946918e-02]]
Traced<ShapedArray(float32[2,2])>with<DynamicJaxprTrace(level=1/0)>
[[-9.9980973e-02 -1.0283450e-13]
 [-6.6662131e-10 -2.4625501e-01]]


In [7]:
print(k_ff(xt,ys,params),'\n')
print(k_ff_jax(xt,ys,params),'\n')

Traced<ShapedArray(float32[2])>with<BatchTrace(level=2/0)> with
  val = Traced<ShapedArray(float32[2,2])>with<DynamicJaxprTrace(level=1/0)>
  batch_dim = 0
[[ 5.4434085e-01  5.7107426e-12]
 [ 2.9275787e-08 -5.7459497e-01]] 

[[ 5.4434079e-01  5.7107426e-12]
 [ 2.9275787e-08 -5.7459497e-01]] 

